name: PR Build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: volta-cli/action@v4
        with:
          registry-url: "https://npm.pkg.github.com"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build
        run: yarn build
