name: Publish Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_PAT }}
    
      - uses: volta-cli/action@v4
        with:
          registry-url: "https://npm.pkg.github.com"

      # - name: Set up .npmrc
      #   run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
    
      - name: Install dependencies
        run: yarn install --frozen-lockfile
    
      - name: Publish
        run: yarn publish-packages
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "ci: Update package versions" || echo "No changes to commit"
          git push